// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Use a direct relative path to ensure correct type resolution
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_KEY.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    }
  }
});

// Add error logging for debugging
supabase.auth.onAuthStateChange((event, _session) => {
  if (event === 'SIGNED_IN') {
    console.log('Supabase auth: User signed in successfully');
  } else if (event === 'SIGNED_OUT') {
    console.log('Supabase auth: User signed out');
  } else if (event === 'TOKEN_REFRESHED') {
    console.log('Supabase auth: Token refreshed');
  }
});